### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by ugurcura** [coskundeniz/ad_clicker#1]
hi, 
I just met github and i m interesting your this project. I have this errors, what can i do it?

> 

14-05-2021 02:08:58 [ INFO]  21: Changing ip address...
Traceback (most recent call last):
  File "/usr/bin/env/lib/python3.9/site-packages/stem/socket.py", line 535, in _make_socket
    control_socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ad_clicker.py", line 75, in <module>
    main()
  File "/usr/bin/ad_clicker.py", line 57, in main
    change_ip_address(password)
  File "/usr/bin/ad_clicker.py", line 22, in change_ip_address
    with Controller.from_port(port=9051) as controller:
  File "/usr/bin/env/lib/python3.9/site-packages/stem/control.py", line 1033, in from_port
    control_port = stem.socket.ControlPort(address, port)
  File "/usr/bin/env/lib/python3.9/site-packages/stem/socket.py", line 503, in __init__
    self.connect()
  File "/usr/bin/env/lib/python3.9/site-packages/stem/socket.py", line 172, in connect
    self._socket = self._make_socket()
  File "/usr/bin/env/lib/python3.9/site-packages/stem/socket.py", line 538, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [Errno 111] Connection refused

thank you

**Comment by coskundeniz** [comment]
* You should first run the **./ad_clicker_setup.sh**
* Make sure that you are in the virtual environment. (**(env)** [coskun@deniz: ~/github/ad_clicker]$)
* Finally run the script (python ad_clicker.py -q "your search query")

**Comment by coskundeniz** [comment]
Related to missing setup on users' local environment.
