### ISSUE TITLE
Errors when using Proxys

### ISSUE THREAD

**Issue by SmallCoffeeCup** [coskundeniz/ad_clicker#20]
Hi,

Really cool python stuff you got here. Apologies before hand if this is a noobier question, but im getting this error when using proxies. It looks like its having trouble connecting and I'm not sure where to go. I saw another user was having issues with it being in incognito mode so I removed it from my command line, but still no luck. 

-----------------------------------------------------------------

PS C:\Users\Small Coffee Cup\Documents\ad_clicker> python ad_clicker.py -q "wireless keyboard" --auth -p 171718:QstW95jgX@154.9.35.212:8800 -e "amazon"

03-05-2023 16:11:43 [ INFO] 241: Using proxy: 171718:QstW95jgX@154.9.35.212:8800
Traceback (most recent call last):
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection 
failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000023D3E53BF50>, 'Connection to 154.9.35.212 timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 487, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ipv4.webshare.io', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000023D3E53BF50>, 'Connection to 154.9.35.212 timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Small Coffee Cup\Documents\ad_clicker\ad_clicker.py", line 98, in <module>
    main()
  File "C:\Users\Small Coffee Cup\Documents\ad_clicker\ad_clicker.py", line 83, in main
    driver = create_webdriver(proxy, args.auth, args.headless, args.incognito)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Small Coffee Cup\Documents\ad_clicker\utils.py", line 266, in create_webdriver
    lat, long = get_location(geolocation_db_client, proxy, auth)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Small Coffee Cup\Documents\ad_clicker\utils.py", line 72, in get_location
    response = requests.get(
               ^^^^^^^^^^^^^
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='ipv4.webshare.io', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000023D3E53BF50>, 'Connection to 154.9.35.212 timed out. (connect timeout=None)'))
Exception ignored in: <function Chrome.__del__ at 0x0000023D3F4176A0>

Traceback (most recent call last):
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 788, in __del__
  File "C:\Users\Small Coffee Cup\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 743, in quit
OSError: [WinError 6] The handle is invalid

**Comment by coskundeniz** [comment]
It does not seem a problem of your proxy but from one of the addresses the tool sends a request. Can you access the "ipv4.webshare.io" address manually on your browser?

**Comment by SmallCoffeeCup** [comment]
yep seems to work, it just loads a landing page with an IP address when I go there.

**Comment by coskundeniz** [comment]
It seems temporary to me but if you still have the problem, you can reserve a slot from the following link for tomorrow and we can take a look.
https://calendly.com/coskundeniz/30min

**Comment by SmallCoffeeCup** [comment]
Just getting back here it looks like its something with the proxies from  Instant Proxies. Im gonna look into webshare and report back

**Comment by coskundeniz** [comment]
Related to proxy provider.
