### ISSUE TITLE
 [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by udemezue01** [coskundeniz/ad_clicker#3]
Thank you for putting this out, I was able to configure this code but I get the following error.

`
Enter tor password: 
26-08-2022 14:36:07 [ INFO]  20: Changing ip address...
Traceback (most recent call last):
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\socket.py", line 535, in _make_socket
    control_socket.connect((self.address, self.port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JS\Desktop\Traffic-Bot\ad_clicker\ad_clicker.py", line 76, in <module>
    main()
  File "C:\Users\JS\Desktop\Traffic-Bot\ad_clicker\ad_clicker.py", line 58, in main
    change_ip_address(password)
  File "C:\Users\JS\Desktop\Traffic-Bot\ad_clicker\ad_clicker.py", line 21, in change_ip_address
    with Controller.from_port(port=9051) as controller:
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\control.py", line 1033, in from_port
    control_port = stem.socket.ControlPort(address, port)
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\socket.py", line 503, in __init__
    self.connect()
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\socket.py", line 172, in connect
    self._socket = self._make_socket()
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\socket.py", line 538, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [WinError 10061] No connection could be made because the target machine actively refused it
(env) 
JS@Udemezue MINGW64 ~/Desktop/Traffic-Bot/ad_clicker (main)
$ python ad_clicker.py -q "how to get started in tech with no experience" -b chrome -t 3000
Enter tor password: 
26-08-2022 14:36:19 [ INFO]  20: Changing ip address...
Traceback (most recent call last):
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\socket.py", line 535, in _make_socket
    control_socket.connect((self.address, self.port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JS\Desktop\Traffic-Bot\ad_clicker\ad_clicker.py", line 76, in <module>
    main()
  File "C:\Users\JS\Desktop\Traffic-Bot\ad_clicker\ad_clicker.py", line 58, in main
    change_ip_address(password)
  File "C:\Users\JS\Desktop\Traffic-Bot\ad_clicker\ad_clicker.py", line 21, in change_ip_address
    with Controller.from_port(port=9051) as controller:
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\control.py", line 1033, in from_port
    control_port = stem.socket.ControlPort(address, port)
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\socket.py", line 503, in __init__
    self.connect()
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\socket.py", line 172, in connect
    self._socket = self._make_socket()
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\socket.py", line 538, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [WinError 10061] No connection could be made because the target machine actively refused it
(env) 
JS@Udemezue MINGW64 ~/Desktop/Traffic-Bot/ad_clicker (main)
$ python ad_clicker.py -q "how to get started in tech with no experience" -b chrome -t 3000
Enter tor password: 
26-08-2022 14:36:56 [ INFO]  20: Changing ip address...
Traceback (most recent call last):
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\socket.py", line 535, in _make_socket
    control_socket.connect((self.address, self.port))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JS\Desktop\Traffic-Bot\ad_clicker\ad_clicker.py", line 76, in <module>
    main()
  File "C:\Users\JS\Desktop\Traffic-Bot\ad_clicker\ad_clicker.py", line 58, in main
    change_ip_address(password)
  File "C:\Users\JS\Desktop\Traffic-Bot\ad_clicker\ad_clicker.py", line 21, in change_ip_address
    with Controller.from_port(port=9051) as controller:
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\control.py", line 1033, in from_port
    control_port = stem.socket.ControlPort(address, port)
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\socket.py", line 503, in __init__
    self.connect()
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\socket.py", line 172, in connect
    self._socket = self._make_socket()
  File "C:\Users\JS\Desktop\Traffic-Bot\env\lib\site-packages\stem\socket.py", line 538, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [WinError 10061] No connection could be made because the target machine actively refused it
`

**Comment by coskundeniz** [comment]
It seems that you are using Windows, but this setup is for Linux. Some settings like port numbers can be different or you may need to check your firewall settings to allow the port etc.

**Comment by udemezue01** [comment]
Thanks, I will do so, I use Windows.
