### ISSUE TITLE
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

### ISSUE THREAD

**Issue by 01odrsw** [coskundeniz/ad_clicker#39]
If i use ad_clicker.py with manual args - everything works. but if i use run_ad_clicker.py, i see that error:
**TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'**
even if use -bc 1, the error keeps appearing

Traceback (most recent call last):
  File "C:\Users\User2\Desktop\test\ad_clicker.py", line 153, in <module>
    main()
  File "C:\Users\User2\Desktop\test\ad_clicker.py", line 122, in main
    driver = create_webdriver(proxy, args.auth, args.headless, args.incognito)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User2\Desktop\test\utils.py", line 362, in create_webdriver
    driver = undetected_chromedriver.Chrome(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User2\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 441, in __init__
    super(Chrome, self).__init__(
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

**Comment by coskundeniz** [comment]
I don't have a problem running. Make sure that you have the latest Chrome version, installed dependencies in requirements.txt, and activated your environment before running. Thanks.
